name: Deploy docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          # Set a SSH private key from repository secret value for pushing to the remote branch.
          # deploy_key: # optional
          # Set a generated GITHUB_TOKEN for pushing to the remote branch.
          # github_token: # optional
          # Set a personal access token for pushing to the remote branch.
          # personal_token: # optional
          # Set a target branch for deployment.
          publish_branch: gh-pages
          # Set an input directory for deployment.
          publish_dir: docs
          # Set an destination subdirectory for deployment.
          destination_dir: /
          # If existing files in the publish branch should be not removed before deploying
          keep_files: false
          # Keep only the latest commit on a GitHub Pages branch
          force_orphan: false
          # Set tag message
          tag_message: # optional
          # Enable the GitHub Pages built-in Jekyll
          enable_jekyll: true
          # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
          # disable_nojekyll: # optional, default is false
          # Set custom domain
          # cname: # optional
          # Set files or directories to exclude from a publish directory.
          # exclude_assets: # optional, default is .github
